### Get all nodes
GET http://{{app}}/api/nodes/
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

### Add nodes
PUT http://{{app}}/api/nodes/test1?address=222.201.145.145:2381
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

### Get the node
GET http://{{app}}/api/nodes/test1
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

### Remove node
DELETE http://{{app}}/api/nodes/zedd-TM1701
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

###
POST http://{{app}}/discovery/nodes/zedd-TM1701
Accept: application/json
Content-Type: application/json
X-Auth-Token: {{auth_token}}

{"name": 1}

###